setwd("C:/Users/HCHO/Documents/MATLAB/keutsch-PlantHub/eng/scripts/R")
library(R.matlab)
library(car)
library(dplyr)
library(ggpubr)
require(lmodel2)
source('YorkFit.R')

##INITIALIZATION############################################
setwd("D:/Plant/RAW/190606.1")
data <- readMat("chamber_blank_output_R_StepsAveraged.mat")

# Specify x and y columns and their associated standard deviations (SD)

x       <- data$bypass.HCHO        # Mean bypass HCHO for each step
sigma_x <- data$bypass.HCHO.std    # Standard deviation of the mean bypass HCHO
y       <- data$chamber.HCHO       # Mean chamber HCHO for each step
sigma_y <- data$chamber.HCHO.std   # Standard deviation of the mean chamber HCHO

x_rpts <- data$bypass.random.pts   # Randomly (normal dist) generated bypass points (derived from each step's bypass avg and std dev)
y_pts   <- data$chamber.HCHO.pts   # Individual chamber HCHO at each step (averaging time specified in m file)
ygroups <- (data$chamber.groups)   # Group each of the individual chamber HCHO by their respective step

############################################################

plot(x,y)
plot(x_rpts,y_pts)

print(paste("Number of Points (N): ", length(x), sep=""))

#Apply Type II Regression from R (also calculates OLS)
# TypeII <- lmodel2(y ~ x, data=data, nperm=250)
# TypeI <- lm(y ~ x, data=data)
print("The York Fit Coefficients")
York_results = YorkFit(x,y,sigma_x,sigma_y,printCoefs=1, makeLine=1)

York_slope    <- York_results[2,1]
York_slope_se <- York_results[2,2]
York_int      <- York_results[1,1]
York_int_se   <- York_results[1,2]

# Calculate residuals
# First we need to generate bypass values for each chamber point given a step's bypass mean and std dev

yhat         <- York_slope*x + York_int  # Predicted values from fit

e_Yorkslopex <- sqrt((York_slope_se/York_slope)^2+(sigma_x/x)^2)*(York_slope)*x
e_yhat       <- sqrt(e_Yorkslopex^2 + York_int_se^2)

York_res     <- y - yhat
York_res_err <- sqrt(sigma_y^2 + e_yhat^2)
York_res_var <- York_res_err^2

plot(x,York_res_var)
title('Uniform Variance of Residuals - Visual Check')

## TESTING FOR NORMALITY
# Perform Shapiro-Wilk Test for testing normality of residuals
print(shapiro.test(York_res))

# Perform Kolmogrov-Smirnov Test to test for normality of residuals 
# print(ks.test(York_res,'pnorm',alternative = "two.sided"))

# Plot QQ Plot - QQ Plots help to show how the sample distribution compares to a normal (Gaussian) distribution
print(ggqqplot(York_res,title = 'Normality of the Residuals'))


## TESTING FOR HOMOSCEDACITY (Uniform variance in both x and y)
# Want null hypothesis to show that the variances are the same; Use Levene's Test

yhat         <- York_slope*x_rpts + York_int  # Predicted values from fit
York_res     <- y_pts - yhat

print(leveneTest(as.numeric(York_res),as.factor(ygroups),center=mean))

# Technically, this applies to OLS only
print(ncvTest(lm(y~x)))

#York_fitted_values <- York_slope*x + York_int
#plot(York_fitted_values, York_res)
#abline(h = 0, untf = FALSE)




# Bartlett Test Homoscedascisity 
#print(bartlett.test(as.numeric(York_res),myData$ShitGroup))

# Fligner-Killeen Test of Homoscedascisity 
#print(fligner.test(as.numeric(York_res),myData$ShitGroup))

#print(ncvTest(lm(y~x)))

#print(ggqqplot(var_x,title = 'Normality in Bypass HCHO'))
#print(ggqqplot(var_y,title = 'Normality in Chamber HCHO'))

#print(var.test(var_x, var_y, alternative = "two.sided"))

#var_grouped <- c(var_x,var_y)
#group <- as.factor(c(rep(1, length(x)), rep(2, length(y))))
#print(fligner.test(var_grouped,group,center=median))


# print("")
# print("lmodel2 Results")
# print(TypeII$regression.results)
# print(TypeII$confidence.intervals)

# print("R-squared")
# print(TypeII$rsquare)

#Extract coefficients from the Type 2 Regressions
# ab.sma = as.numeric(TypeII$regression.results[3,2:3])

# par(ps = 18, cex = 1, cex.main = 1)
# plot(x, y, type="p", col="blue",xlab="Chamber / ppbv",ylab="Normalized Flux")
# abline(a=York[1], b=York[2], col="red", lwd=3)

# print("Heteroscedacity Test")
# print(ncvTest(TypeI)) #Heteroscedacity Test: Both these test have a p-value less 
# that a significance level of 0.05, therefore we can reject the null hypothesis 
# that the variance of the residuals is constant and infer that heteroscedasticity
# is indeed present, thereby confirming our graphical inference.
