function pplantesht(varargin);
% pplantesht( [...] );
% Eng SHT state
h = timeplot({'SHT31_state'}, ...
      'Eng SHT state', ...
      'SHT state', ...
      {'SHT31\_state'}, ...
      varargin{:} );
