function pplantesht_err(varargin);
% pplantesht_err( [...] );
% Eng SHT err
h = timeplot({'SHT31_I2C_err'}, ...
      'Eng SHT err', ...
      'SHT err', ...
      {'SHT31\_I2C\_err'}, ...
      varargin{:} );
