function pplantecrc(varargin);
% pplantecrc( [...] );
% Eng CRC err
h = timeplot({'SHT31_CRC_err'}, ...
      'Eng CRC err', ...
      'CRC err', ...
      {'SHT31\_CRC\_err'}, ...
      varargin{:} );
