function pplantlicorstale(varargin);
% pplantlicorstale( [...] );
% LICOR Stale
h = timeplot({'LICOR_Stale'}, ...
      'LICOR Stale', ...
      'Stale', ...
      {'LICOR\_Stale'}, ...
      varargin{:} );
