function pplantswssws(varargin)
% pplantswssws( [...] );
% SW Status SW Stat
h = timeplot({'SWStat'}, ...
      'SW Status SW Stat', ...
      'SW Stat', ...
      {'SWStat'}, ...
      varargin{:} );
