function pplanteb(varargin);
% pplanteb( [...] );
% Eng Bits
h = ne_dstat({
  'Error', 'I2C_intflag', 7; ...
	'SB', 'I2C_intflag', 1; ...
	'MB', 'I2C_intflag', 0; ...
	'RXNACK', 'I2C_status', 2; ...
	'ARBLOST', 'I2C_status', 1; ...
	'BUSERR', 'I2C_status', 0 }, 'Bits', varargin{:} );
