function pplantets_error(varargin);
% pplantets_error( [...] );
% Eng TS error
h = timeplot({'TS_error'}, ...
      'Eng TS error', ...
      'TS error', ...
      {'TS\_error'}, ...
      varargin{:} );
