function pplantswsflag2(varargin);
% pplantswsflag2( [...] );
% SW Status Flag 2
h = timeplot({'Flag2'}, ...
      'SW Status Flag 2', ...
      'Flag 2', ...
      {'Flag2'}, ...
      varargin{:} );
