function pplantshts(varargin);
% pplantshts( [...] );
% SHT31 Status
h = ne_dstat({
  'Pending', 'SHT31_Status', 15; ...
	'Heater', 'SHT31_Status', 13; ...
	'RHtrack', 'SHT31_Status', 11; ...
	'SysRst', 'SHT31_Status', 4; ...
	'CmdErr', 'SHT31_Status', 1; ...
	'WCksum', 'SHT31_Status', 0 }, 'Status', varargin{:} );
