function pplantlicorho(varargin);
% pplantlicorho( [...] );
% LICOR H2O ppth
h = timeplot({'H2O_ppth'}, ...
      'LICOR H2O ppth', ...
      'H2O ppth', ...
      {'H2O\_ppth'}, ...
      varargin{:} );
